version: '3.1'

services:  # containers. same as docker run
  my_drupal: # a friendly name. this is also DNS name inside network
    image: drupal
#    command: # Optional, replace the default CMD specified by the image
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: t0ps3cret
    depends_on: 
      - my_postgres
    ports:
      - 8080:80
    volumes:
      - "/Users/vadim/Projects/Docker/tmp/drupal_modules:/var/www/html/modules"
      - "/Users/vadim/Projects/Docker/tmp/drupal_profiles:/var/www/html/profiles"
      - "/Users/vadim/Projects/Docker/tmp/drupal_themes:/var/www/html/themes"
      - "/Users/vadim/Projects/Docker/tmp/drupal_sites:/var/www/html/sites"
    links:
      - my_postgres:postgres
  my_postgres:
    image: postgres
#    command: # Optional, replace the default CMD specified by the image
    environment:
        POSTGRES_PASSWORD: t0ps3cret
    volumes:
      - "/Users/vadim/Projects/Docker/tmp/postgres:/var/lib/postgresql/data"


#volumes: # Optional, same as docker volume create

#networks: # Optional, same as docker network create



